### ISSUE TITLE
How to use your ports overlay repo?

### ISSUE THREAD

**Issue by graemeg** [er2off/freebsd-ports#1]
Not an issue, but I was curious how you use the freebsd-ports overlay repo of yours?  Do you clone it into the usual `/usr/ports` location?

**Comment by er2off** [comment]
As I know, ports overlay support [was added](https://reviews.freebsd.org/D21468) but currently I simply clone repo to somewhere and use cd category/port && make clean install

**Comment by graemeg** [comment]
Thank you. I tried out this repo, and then tried to compile your port of `prism-launcher` (rebranded MultiMC), but got the following error:

```
===>   prism-launcher-8.0 depends on file: /usr/local/sbin/pkg - found
=> PrismLauncher-PrismLauncher-8.0_GH0.tar.gz doesn't seem to exist in /usr/ports/distfiles/.
=> /usr/ports/distfiles/ is not writable by you; cannot fetch.
*** Error code 1

Stop.
```

How do I get hold of the `*_GH0.tar.gz `file, and then matching the SHA256's mentioned in the `distinfo` file?

**Comment by er2off** [comment]
This is because you probably run as user, not as root (`/usr/ports/distfiles/ is not writable by you`). Main ports tree switch you to root but this doesn't happen somehow with this overlay.

Prism Launcher should be fetchable.

**Comment by er2off** [comment]
Also I added makefiles in https://github.com/er2off/freebsd-ports/commit/1ee6a82625928f36f6553937b6352b13170399f3 to build everything using (su/doas/sudo) make clean reinstall (probably target should be package, you don't need everything)

**Comment by er2off** [comment]
I set up localhost poudriere build server for this overlay. Maybe I will publish binary repository too.

![image](https://github.com/er2off/freebsd-ports/assets/46158549/34b1ee66-f740-495c-a9a8-bbfc6b7b9fb3)

**Comment by jsm222** [comment]
PORTREVISION must be an integer you have snapshot+2 that is what gives error 1

**Comment by er2off** [comment]
> PORTREVISION must be an integer you have snapshot+2 that is what gives error 1

Yes, this shouldn't be but lwjgl3.3.4 isn't out yet.

**Comment by er2off** [comment]
I described everything in readme so I think this issue can be closed.
