### ISSUE TITLE
Prism Launcher should require qt6-svg dependency for it's icons.

### ISSUE THREAD

**Issue by ghost** [er2off/freebsd-ports#3]
Hi. I noticed that `qt6-svg` package is required for Prism Launcher's icons. Installing it makes icons to appear.

**Comment by ghost** [comment]
I made a PR #5  about that. Here is how it looks if `qt6-svg` isn't installed.

# Before
![2024-06-27-182027_1366x768_scrot](https://github.com/er2off/freebsd-ports/assets/153529729/f1914c0f-a1e9-4b57-9240-cc9544416538)
# After
![2024-06-27-182037_1366x768_scrot](https://github.com/er2off/freebsd-ports/assets/153529729/c0df4d16-260d-4495-82dd-9491731a7d20)

**Comment by er2off** [comment]
Merged.
